In [1]:
import requests
import numpy as np

x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [2]:
raw_data=[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
for sample in raw_data:
    if len(sample)<1:
        continue
    for i,value in enumerate(sample[:4]):
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0
        


In [3]:
#print(raw_data[:3])

###문자열 --> 숫자
* setosa -> 0
* versicolour -> 1
* virginica -> 2


In [4]:
for sample in raw_data:
    sample[-1] = 0.0
#print(raw_data[:3])

In [38]:
for sample in raw_data:
    if len(sample)<2:
        continue
    if 'setosa' in sample[-1]:
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0
        


TypeError: argument of type 'float' is not iterable

In [5]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])

[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 0.0]
[5.8, 2.7, 5.1, 1.9, 0.0]


In [6]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]

[[5.9, 3.0, 5.1, 1.8, 0.0], [0.0], [0.0]]
152


In [7]:
np_data = np.array(raw_data)
np_data.shape
np_data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계값
* 전체 평균, 표준편차 - sepal length, sepal witdh, petal length, petal width
* 품종별 평균, 표준편차

* 평균 np.mean()
* 표준편차 np.std()

In [30]:
print(np_data[:3])

avg= (np_data[:150].sum(axis = 0))

print('평균값: ', avg / 150)







[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]]
평균값:  [5.84333333 3.054      3.75866667 1.19866667 0.        ]


In [32]:
import math

def mean(num_list): # 평균
    return sum(num_list)/len(num_list)

def mean2(num_list):
    sum_valu=()
    for i in num_list:
        sum_value += i
    return sum_value / len(num_list)

def median(num_list):  #중앙값
    num_list.sort()
    if len(num_list)%2==1:
        i = (len(num_list))//2
        return num_list[i]
    else:
        i = len(num_list)//2
        return (num_list[i] + num_list[i-1])/2
    
    
def dev(num_list): #편차
    m = mean(num_list)
    return [x-m for x in num_list]


def var(num_list): #분산
    n = len(num_list)
    d = dev(num_list)
    return sum([x*x for x in d])/(n-1)


def covar(list_1,list_2): #공분산
    n = len(list_1)
    list_1_dev = dev(list_1)
    list_2_dev = dev(list_2)
    return sum(x * y for x, y in zip(list_1_dev, list_2_dev))/(n-1)


def corel(list_1, list_2): # 상관도 (-1 ~ 1)  마이너스라도 1에 가까우면 상관도 높음
    return covar(list_1, list_2)/(stdev(list_1)*stdev(list_2))


def stdev(num_list): #표준편차  (분산에 루트)
    return math.sqrt(var(num_list))

In [38]:
print(np_data[:3])
print(np.mean(np_data, axis = 0))
print(np.std(np_data, axis = 0))
print(np.corrcoef(np_data))  #상관도 

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]]
[5.84333333 3.054      3.75866667 1.19866667 0.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.        ]
[[1.         0.99706483 0.99997795 ... 0.76012976 0.74288374 0.74758347]
 [0.99706483 1.         0.99750791 ... 0.79227347 0.77022724 0.77699657]
 [0.99997795 0.99750791 1.         ... 0.76347554 0.74599502 0.75068712]
 ...
 [0.76012976 0.79227347 0.76347554 ... 1.         0.99467533 0.99731867]
 [0.74288374 0.77022724 0.74599502 ... 0.99467533 1.         0.99753337]
 [0.74758347 0.77699657 0.75068712 ... 0.99731867 0.99753337 1.        ]]


In [44]:
filter_setosa = np_data[:,-1]==0.0
filter_versicolor = np_data[:, -1]==1.0
filter_virginica = np_data[:,-1]==2.0

print(np.mean(np_data[filter_setosa], axis = 0))
print(np.std(np_data[filter_setosa], axis = 0))  #다른 꽃들도 똑같이

[5.84333333 3.054      3.75866667 1.19866667 0.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.        ]
