In [2]:
import numpy as np  #https://compmath.korea.ac.kr/appmath/NumpyBasics.html

a1 = np.array([[1,2,3], [10,20,30]])  #numpy패키지안의 array는 클래스이름을 nbarray라고 지어놓음 만들때는 array라고 사용
print(a1)
print(a1.ndim)
print(a1.shape)  #ndarray로 작업시 항상 염두
print(a1.size)  

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [2]:
a2 = np.arange(20).reshape(4,5) #갯수가 맞아떨어져야함 / 안의 데이터 타입이 전부 같아야함
print(a2)
print(a2.shape)  #(20, )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [3]:
a3 = a2.flatten()  #1차원으로 만들어준다 deep copy 원본을 그대로 카피 (개별적으로 카피함)
a3[3] = 100
print(a3)
print(a2)


a4 = a2.ravel() #shallow copy 원본의 참조값을 가져옴    //일반적으로 flatten사용
a4[3] = 200
print(a4)
print(a2)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [3]:
a2 = np.arange(20).reshape(4,5)  #split 내가 원하는 부분만 썰어옴
print(a2)
#print(a2[1])
#print(a2[1,2])
print(a2[:,1]) #모든 샘플에 대해서 인덱스1인 칼럼만 가져와라
#print(a2[:,1:4]) #첫번째는 지나감 1 : 4 = [1,2,3] 1시작 4아래
#print(a2[:,1:4:2])
#print(a2[1, :]) 
#print(a2[1:3, :])
print(a2[::2, :])  #하나 거르고 하나 가져오기
print(a2[::2, 1:4]) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 1  6 11 16]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 1  2  3]
 [11 12 13]]


In [23]:
print(a2)  #데이터 분석시엔 한줄이 하나의 튜플(샘플)이라 칭함
print(a2.shape)  #axis
#print(a2.sum())
print(a2.sum(axis = 0))  #축끼리 더한값
print(a2.sum(axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
190
[30 34 38 42 46]
[10 35 60 85]


In [25]:
print(a2, a2.shape)
a3 = a2.T  #축 바꿈 T = transform
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [30]:
print(a2, a2.shape)
a3 = np.moveaxis(a2, [0], [1])  #출발점 /목표점
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [5]:
a10 = np.arange(5,20).reshape(3,5)
print(a10, a10.shape)
      
#shape (3,5)의 2차원 ndarray로 만들기
#print(a10[::, 2:4])
a11 = a10[:, 2:4]
print(a11,a11.shape)
print(a11.sum(axis=0))
#print(a10[::, 2:4].sum(axis = 0))

print(np.mean(a11, axis = 0))

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)
[[ 7  8]
 [12 13]
 [17 18]] (3, 2)
[36 39]
[12. 13.]


In [58]:
a1 = np.arange(0,10).reshape(2,5)  
a2 = np.arange(100,110).reshape(2,5)
print(a1)
print(a2)

a3 = np.concatenate((a1,a2),axis = 1)  #튜플형태로
print(a3)
a4 = np.hstack((a1,a2))  #다른방법으로 붙이기
print(a4)
a5 = np.vstack((a1,a2))
print(a5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [63]:
print(a4)  #hsplit / vsplit등 사용법 
a6 = np.hsplit(a4,5)
print(a6)

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


In [64]:
a7 = a4.T
print(a7)
np.vsplit(a7,5)

[[  0   5]
 [  1   6]
 [  2   7]
 [  3   8]
 [  4   9]
 [100 105]
 [101 106]
 [102 107]
 [103 108]
 [104 109]]


[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [69]:
a2 = np.arange(20).reshape(4,5)
print(a2)
filter1 = (a2[:,0] %10==5)
print(filter1)
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[False  True False  True]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
